"""initial schema (master_plan v0.3 §15)

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-11 00:00:00

Hand-written rather than autogenerated, so the SQL exactly matches
master_plan §15 (CHECK names, index names, partial index, pgcrypto extension).
Idempotency notes:
- `pgcrypto` extension installed for `gen_random_uuid()`.
- All FKs have explicit ON DELETE behaviour (CASCADE for user-owned rows).
- `proactive_insights` index is partial: only rows with is_dismissed=FALSE.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gen_random_uuid() lives in pgcrypto.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ----- users -----
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "parent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_users_parent_id_users"),
            nullable=True,
        ),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column(
            "finance_level",
            sa.String(),
            nullable=False,
            server_default=sa.text("'beginner'"),
        ),
        sa.Column(
            "is_demo",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint(
            "role IN ('parent','child','individual')",
            name="role_valid",
        ),
        sa.CheckConstraint(
            "finance_level IN ('beginner','intermediate','advanced','child')",
            name="finance_level_valid",
        ),
    )

    # ----- categories -----
    op.create_table(
        "categories",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_categories_user_id_users"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "parent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("categories.id", name="fk_categories_parent_id_categories"),
            nullable=True,
        ),
        sa.Column("budget_monthly", sa.Numeric(12, 2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # ----- transactions -----
    op.create_table(
        "transactions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_transactions_user_id_users"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "category_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("categories.id", name="fk_transactions_category_id_categories"),
            nullable=True,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("merchant", sa.String(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.String(),
            nullable=False,
            server_default=sa.text("'manual'"),
        ),
        sa.Column("receipt_image_url", sa.String(), nullable=True),
        sa.Column("raw_ocr_data", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.CheckConstraint(
            "type IN ('income','expense')",
            name="type_valid",
        ),
        sa.CheckConstraint(
            "source IN ('manual','receipt_ocr','recurring')",
            name="source_valid",
        ),
    )
    op.create_index(
        "idx_tx_user_date",
        "transactions",
        ["user_id", sa.text("occurred_at DESC")],
    )
    op.create_index("idx_tx_category", "transactions", ["category_id"])
    op.create_index("idx_tx_merchant", "transactions", ["merchant"])

    # ----- subscriptions -----
    op.create_table(
        "subscriptions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_subscriptions_user_id_users"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("merchant", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("billing_cycle", sa.String(), nullable=False),
        sa.Column("next_billing_date", sa.Date(), nullable=True),
        sa.Column(
            "category_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "categories.id", name="fk_subscriptions_category_id_categories"
            ),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("TRUE"),
        ),
        sa.Column(
            "detected_from_transactions",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
        sa.Column("usage_score", sa.Numeric(3, 2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.CheckConstraint(
            "billing_cycle IN ('weekly','monthly','yearly')",
            name="billing_cycle_valid",
        ),
    )

    # ----- conversations -----
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_conversations_user_id_users"),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # ----- messages -----
    op.create_table(
        "messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "conversation_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "conversations.id",
                ondelete="CASCADE",
                name="fk_messages_conversation_id_conversations",
            ),
            nullable=True,
        ),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(), nullable=True),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant','tool')",
            name="role_valid",
        ),
    )
    op.create_index("idx_msg_conv", "messages", ["conversation_id", "created_at"])

    # ----- agent_memory -----
    op.create_table(
        "agent_memory",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_agent_memory_user_id_users"),
            nullable=False,
        ),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.UniqueConstraint("user_id", "key", name="agent_memory_user_id_key_key"),
    )

    # ----- proactive_insights -----
    op.create_table(
        "proactive_insights",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "users.id", ondelete="CASCADE", name="fk_proactive_insights_user_id_users"
            ),
            nullable=False,
        ),
        sa.Column("insight_type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.String(),
            nullable=False,
            server_default=sa.text("'info'"),
        ),
        sa.Column("action_label", sa.String(), nullable=True),
        sa.Column(
            "is_dismissed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.CheckConstraint(
            "severity IN ('info','warning','critical')",
            name="severity_valid",
        ),
    )
    # Partial index — matches master_plan §15 exactly.
    op.create_index(
        "idx_insight_user",
        "proactive_insights",
        ["user_id", sa.text("created_at DESC")],
        postgresql_where=sa.text("is_dismissed = FALSE"),
    )


def downgrade() -> None:
    # Reverse order of upgrade (FK dependencies).
    op.drop_index("idx_insight_user", table_name="proactive_insights")
    op.drop_table("proactive_insights")

    op.drop_table("agent_memory")

    op.drop_index("idx_msg_conv", table_name="messages")
    op.drop_table("messages")

    op.drop_table("conversations")
    op.drop_table("subscriptions")

    op.drop_index("idx_tx_merchant", table_name="transactions")
    op.drop_index("idx_tx_category", table_name="transactions")
    op.drop_index("idx_tx_user_date", table_name="transactions")
    op.drop_table("transactions")

    op.drop_table("categories")
    op.drop_table("users")

    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
